
version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: restaurant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  zookeeper:
    image: confluentinc/cp-zookeeper

  kafka:
    image: confluentinc/cp-kafka
