
spring:
  kafka:
    bootstrap-servers: localhost:9092

  datasource:
    url: jdbc:postgresql://localhost:5432/notifications
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
